// Columns follow LANGUAGES: fr, en, pt_BR, es, it, ru, ku, ckb, zh, de.
export const albumMessages: Record<string, readonly [string, string, string, string, string, string, string, string, string, string]> = {
  "Ta collection": ["Ta collection", "Your collection", "Sua coleção", "Tu colección", "La tua collezione", "Твоя коллекция", "Koleksiyona te", "کۆکراوەکەت", "你的收藏", "Deine Sammlung"],
  "Chaque découverte compte.": ["Chaque découverte compte.", "Every discovery counts.", "Cada descoberta conta.", "Cada descubrimiento cuenta.", "Ogni scoperta conta.", "Каждое открытие важно.", "Her keşf girîng e.", "هەموو دۆزینەوەیەک گرنگە.", "每次发现都值得珍藏。", "Jede Entdeckung zählt."],
  "{{caught}} sur {{total}} portraits trouvés": ["{{caught}} sur {{total}} portraits trouvés", "{{caught}} of {{total}} portraits found", "{{caught}} de {{total}} retratos encontrados", "{{caught}} de {{total}} retratos encontrados", "{{caught}} di {{total}} ritratti trovati", "Найдено {{caught}} из {{total}} портретов", "{{caught}} ji {{total}} portre hatine dîtin", "{{caught}} لە {{total}} وێنە دۆزراوەتەوە", "已找到 {{caught}}/{{total}} 幅肖像", "{{caught}} von {{total}} Porträts gefunden"],
  "Collections": ["Collections", "Collections", "Coleções", "Colecciones", "Collezioni", "Коллекции", "Koleksiyon", "کۆکراوەکان", "收藏系列", "Sammlungen"],
  "Collection complète !": ["Collection complète !", "Collection complete!", "Coleção completa!", "¡Colección completa!", "Collezione completa!", "Коллекция собрана!", "Koleksiyon temam e!", "کۆکراوەکە تەواوە!", "系列已集齐！", "Sammlung vollständig!"],
  "À toi de les retrouver": ["À toi de les retrouver", "Find them all", "Encontre todos", "Encuéntralos todos", "Trovali tutti", "Найди их всех", "Hemûyan bibîne", "هەموویان بدۆزەرەوە", "等你来发现", "Finde sie alle"],
  "Tous les portraits": ["Tous les portraits", "All portraits", "Todos os retratos", "Todos los retratos", "Tutti i ritratti", "Все портреты", "Hemû portre", "هەموو وێنەکان", "全部肖像", "Alle Porträts"],
  "Comment compléter l’album ?": ["Comment compléter l’album ?", "How do I complete the album?", "Como completar o álbum?", "¿Cómo completar el álbum?", "Come completare l’album?", "Как заполнить альбом?", "Çawa albûmê temam bikim?", "چۆن ئەلبوومەکە تەواو بکەم؟", "如何集齐图鉴？", "Wie vervollständige ich das Album?"],
  "Retrouve les portraits en jouant pour remplir ton album.": ["Retrouve les portraits en jouant pour remplir ton album.", "Find portraits as you play to fill your album.", "Encontre retratos ao jogar para preencher seu álbum.", "Encuentra retratos al jugar para llenar tu álbum.", "Trova i ritratti giocando per riempire il tuo album.", "Находи портреты во время игры, чтобы заполнить альбом.", "Dema dilîzî portreyan bibîne da ku albûma xwe tijî bikî.", "لە کاتی یاریکردن وێنەکان بدۆزەرەوە بۆ پڕکردنەوەی ئەلبوومەکەت.", "在游戏中寻找肖像，填满你的图鉴。", "Finde beim Spielen Porträts, um dein Album zu füllen."],
  "Médailles": ["Médailles", "Medals", "Medalhas", "Medallas", "Medaglie", "Медали", "Medalya", "میدالیاکان", "勋章", "Medaillen"],
  "Retrouve le même portrait pour gagner des médailles.": ["Retrouve le même portrait pour gagner des médailles.", "Find the same portrait again to earn medals.", "Encontre o mesmo retrato novamente para ganhar medalhas.", "Vuelve a encontrar el mismo retrato para ganar medallas.", "Trova di nuovo lo stesso ritratto per ottenere medaglie.", "Находи один и тот же портрет, чтобы получать медали.", "Heman portreyê dîsa bibîne da ku medalyayan bi dest bixî.", "هەمان وێنە دووبارە بدۆزەرەوە بۆ بەدەستهێنانی میدالیا.", "重复找到同一幅肖像即可获得勋章。", "Finde dasselbe Porträt erneut, um Medaillen zu verdienen."],
  "Prochaine médaille": ["Prochaine médaille", "Next medal", "Próxima medalha", "Próxima medalla", "Prossima medaglia", "Следующая медаль", "Medalyaya din", "میدالیای داهاتوو", "下一枚勋章", "Nächste Medaille"],
};
